
project_id = "oaynfzqjielnsipttzbs"

[functions.odoo-api-proxy]
verify_jwt = false

[functions.fast2sms-otp]
verify_jwt = false

[functions.seller-approval-webhook]
verify_jwt = false

[functions.product-approval-webhook]
verify_jwt = false

[functions.livestock-approval-webhook]
verify_jwt = false

[functions.create-odoo-customer]
verify_jwt = false

[functions.odoo-create-product]
verify_jwt = false
